# This is a basic workflow to help you get started with Actions

name: jest-tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TESTS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run:
          name: Setup Code Climate test-reporter
          command: |
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      # Runs a single command using the runners shell
      - name: Run test
        command: |
          npm install
          ./cc-test-reporter before-build
          make lint
          make test
          ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

      # Runs a set of commands using the runners shell
